### ISSUE TITLE
ID numbers

### ISSUE THREAD

**Issue by katelaurel** [Razevich/crumbs#3]
We need auto-generated unique IDs for projects and solutions.

**Comment by ghost** [comment]
maybe it's a preliminary fix, but make each project id - 1,2,3,4, and every
respective solution for each project is 1.1, 1.2, 1.3, 1.4, 1.5, 1.10, etc.?

On Mon, Feb 8, 2016 at 3:01 PM, katelaurel notifications@github.com wrote:

> We need auto-generated unique IDs for projects and solutions.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Razevich/crumbs/issues/3.

## 

*Kevin Wei *

Microsoft Civic Tech Fellow  www.microsoft-chicago.com

University of Chicago ’17: Economics and Public Policy

kevinwei@uchicago.edu | 630-765-1321 | @wei_too_good

**Comment by Razevich** [comment]
It's already solved
